### ISSUE TITLE
InvalidCastException: Unable to cast object of type 'PatternForCore.Services.MovieServices' to type 'PatternForCore.Services.Base.Contracts.IMovieServices'.

### ISSUE THREAD

**Issue by Diwas777** [senvardarsemih/genericforcore#3]
InvalidCastException: Unable to cast object of type 'PatternForCore.Services.MovieServices' to type 'PatternForCore.Services.Base.Contracts.IMovieServices'. 

I got this error while accessing "**/home/index**"

**Comment by senvardarsemih** [comment]
> InvalidCastException: Unable to cast object of type 'PatternForCore.Services.MovieServices' to type 'PatternForCore.Services.Base.Contracts.IMovieServices'.
> 
> I got this error while accessing "**/home/index**"

i will check this out

**Comment by senvardarsemih** [comment]
I fixed it.So you can pull the latest master branch @Diwas777

**Comment by Diwas777** [comment]
Thanks for your quick response. @senvardarsemih
Works Perfectly. 
...
I have one question:
As your **Read .md** file you have written an **experimental generic pattern,** but
Is it Ok **If I use this pattern for making real enterprise applications**? Thanks in advance.

**Comment by senvardarsemih** [comment]
@Diwas777  You can use it in your real enterprise applications _but it's entirely your responsibility_.
