### ISSUE TITLE
ContextFactory Connectionstring issue

### ISSUE THREAD

**Issue by nihal925** [senvardarsemih/genericforcore#5]
Hi,
I got the DefaultConnection value as null in ContextFactory class, but i have kept the ConnectionStrings' DefaultConnection value in both appsettings and appsettings.development.

**Comment by senvardarsemih** [comment]
Hi, 
Which environment are you launching the project ? maybe you're running up in a different environment than the development environment. If the problem persists, I recommend you to use an in-memory database.

**Comment by nihal925** [comment]
Hi,
I launched the project in development environment only. At very first time, that means at startup ConfigureServies method i have received the connection string but when it gave null exception at the time of posting the data, means IOptions<ConnectionStrings> does not hold any connectionString value.

**Comment by nihal925** [comment]
> Hi, Which environment are you launching the project ? maybe you're running up in a different environment than the development environment. If the problem persists, I recommend you to use an in-memory database.

Hi,
I launched the project in development environment only. At very first time, that means at startup ConfigureServies method i have received the connection string but when i injected IOptions ConnectionStrings in ContextFactory it gives the connectionString value as null.
I am not applied the Identity except remaining all are same what you have done. for that i have changed the DatabaseConext inheritance as 
public class DatabaseContext : **DbContext**, IDatabaseContext
this is the change only i have did

**Comment by nihal925** [comment]
> > Hi, Which environment are you launching the project ? maybe you're running up in a different environment than the development environment. If the problem persists, I recommend you to use an in-memory database.
> 
> Hi, I launched the project in development environment only. At very first time, that means at startup ConfigureServies method i have received the connection string but when i injected IOptions<ConnectionStrings> in ContextFactory it gives the connectionString value as null. I am not applied the Identity except remaining all are same what you have done. for that i have changed the DatabaseConext inheritance as public class DatabaseContext : **DbContext**, IDatabaseContext
This is the only change i have done

**Comment by senvardarsemih** [comment]
Okay, just add ` services.Configure<ConnectionSettings>(options => Configuration.GetSection("ConnectionStrings").Bind(options));` at ConfigureServices section in Startup
